(defun c:CHGATTRIB (/ blkname atttag newcontent ss ent attvals attval)
  (setq ent (car (entsel "\nSelect a block: ")))
  (setq atttag (getstring "\nEnter the tag of the attribute: "))
  (setq newcontent (getstring "\nEnter the new content: "))
  (setq attvals (mapcar 'cdr (vl-remove-if-not '(lambda (x) (equal (cdr (assoc 2 x)) atttag)) (entget ent))))
  (if (not (null attvals))
    (progn
      (setq attval (car attvals))
      (setq attval (subst newcontent (cdr attval) attval))
      (setq attval (cons 1 attval))
      (setq ent (subst attval (assoc 1 (entget ent)) (entget ent)))
      (entmod ent)
      (princ "\nAttribute updated successfully.")
    )
    (princ "\nAttribute not found.")
  )
  (princ)
)
